TILE_SIZE = 30
NUM_ROWS = 20
NUM_COLS = 10
WIDTH = TILE_SIZE * NUM_COLS
HEIGHT = TILE_SIZE * NUM_ROWS
BORDER_WIDTH = 35
INFO_AREA_WIDTH = 300
FPS = 60


# color
BG_COLOR = '#DEDFD1'
LINE_COLOR = '#123456'